### ISSUE TITLE
Retina - Not Online

### ISSUE THREAD

**Issue by Keri-Lynn** [Keri-Lynn/retina-images#1]
@charlie-quinn @thomasjbradley

Done but not online.

![Screenshot (658)](https://user-images.githubusercontent.com/43151336/67523609-07941180-f67d-11e9-8053-f098b80662c1.png)

**Comment by thomasjbradley** [comment]
When you signed into Markbot you didn’t type your GitHub username properly.

I can see in the screenshot that it’s pointing to `keri-lynn-tucker` but your username is `Keri-Lynn` (no `-Tucker`).

Sign out of Markbot & sign back in with the correct GitHub username: `Keri-Lynn`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
